brokerClusterName=StudyPilotDemo
brokerName=demo-broker
brokerId=0
brokerIP1=rocketmq-broker
listenPort=10911
autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH
deleteWhen=04
fileReservedTime=24
